### ISSUE TITLE
Hide other elements based on disable-comments status

### ISSUE THREAD

**Issue by lmartins** [solarissmoke/disable-comments#15]
Hi,

Im building my wp websites using Timber, and i came to the situation where I need to hide other elements not removed by default by disable-comments. Is there any method I can use to achieve this?

Thank you.

**Comment by solarissmoke** [comment]
Hi,

The plugin doesn't currently expose any hooks or actions, but I would be happy to add something. Simplest is just to fire an action such as `comments_disabled` which you can use to trigger your own modifications. Would that be what you are looking for?

**Comment by lmartins** [comment]
Yes, that would solve my problem.
Im just wondering if that `comments_disabled`would also return true if the site is configured to show comments but close new comments after a certain period. 

Anyway, i'll look the info about that action and post here a code sample if I manage to get it working..

Thanks.

**Comment by solarissmoke** [comment]
Just to clarify, there is no `comments_disabled` action in the core. I was suggesting that the plugin introduces one.

**Comment by lmartins** [comment]
Oh, I misunderstood that. Yeah, that would be quite useful.

**Comment by solarissmoke** [comment]
Thinking about it, are you just looking for the [comments_open()](https://developer.wordpress.org/reference/functions/comments_open/) function?

**Comment by lmartins** [comment]
Yeah, for now im using that but I imagine it isn't quite the same because the comments can be open but disabled in you plugin right?

**Comment by solarissmoke** [comment]
No. Comments disabled means comments_open() will return false.

**Comment by solarissmoke** [comment]
Closing this as I think the core `comments_open()` function and filter should provide what you are looking for.

**Comment by lmartins** [comment]
I understand, although I think they are not quite the same, as I can 

- Post allow comments, during commenting period: Function returns true
- Post allow comments, outside commenting period: Function returns false
- Disabled comments, during commenting period: Function returns true
- Disabled comments, outside commenting period: Function returns false

My goal here was to hide parts of the UI in relation to the state given by "disable-comments" plugin.

**Comment by solarissmoke** [comment]
> Disabled comments, during commenting period: Function returns true

If that happened, the theme would display comments! The plugin filters `comments_open()` and will always set it to `false` if comments are disabled (i.e., the situation above should not arise). Please check that you don't have another filter modifying the value at a later stage.

**Comment by lmartins** [comment]
Thanks for the tips Samir.
