### ISSUE TITLE
Persistantly disable comments

### ISSUE THREAD

**Issue by SiegfriedGeryl** [solarissmoke/disable-comments#20]
Hi,

After a user choose to persistantly disable comments, can I still repair this by adding a new (comment) field in the sgl database?
If yes, what field exactly?

Regards

**Comment by szepeviktor** [comment]
> sgl database

Could you explain what "sgl database" is?

**Comment by szepeviktor** [comment]
Uh! SQL, isn't it?

**Comment by szepeviktor** [comment]
After deactivating this plugin you can have comments.

**Comment by szepeviktor** [comment]
https://wordpress.org/plugins/disable-comments/faq/
> Note however that this will make persistent changes: comments will remain closed even if you later disable the plugin (you can always reopen them manually, of course).

**Comment by szepeviktor** [comment]
`wp_posts` table has a field called `comment_status`, set that to `open`
Watch for post_type and post_status!

**Comment by solarissmoke** [comment]
I am not sure this question is even related to this plugin? In any case please use the WordPress support forums for this. Closing as invalid.

**Comment by SiegfriedGeryl** [comment]
Ok, thanks!  It works again.  Had simply to disable the plugin.
PS: I meant SQL, sorry for mistyping ;)
