### ISSUE TITLE
Adds broken link to script to header

### ISSUE THREAD

**Issue by amouratoglou** [solarissmoke/disable-comments#26]
In my case the plugin added the folllowing code to the header, wich gives an error.

`<script type='text/javascript' src='http://siteurl.comArray?ver=1'></script>`

my client legacy theme is called "Miami" from PunchThemes and with no plugins, adds this to the header.

**Comment by solarissmoke** [comment]
I am pretty sure this has nothing to do with the plugin, which doesn't add any headers anywhere. Please check that your site hasn't been compromised and also whether your web host isn't injecting anything into your templates.

Easy way to test: disable the plugin and see if you still see this code.
