### ISSUE TITLE
Disable the Comments Metabox

### ISSUE THREAD

**Issue by garrett-eclipse** [solarissmoke/disable-comments#29]
Hello,

Opening a ticket before I implement an enhancement.

On a post through the Screen Options you can enable the 'Comments' metabox even when comments are disabled globally or for that specific post type;
![screen shot 2016-05-13 at 11 15 31 am](https://cloud.githubusercontent.com/assets/8726005/15257632/1405e0ea-18fc-11e6-8ea6-a3514248a5e2.png)
![screen shot 2016-05-13 at 11 15 37 am](https://cloud.githubusercontent.com/assets/8726005/15257630/138f29dc-18fc-11e6-8be8-5e59d3d3e572.png)
![screen shot 2016-05-13 at 11 15 43 am](https://cloud.githubusercontent.com/assets/8726005/15257629/131af0a8-18fc-11e6-80f1-7cc12b7b905c.png)

Fix I'm implementing is to remove post_type support for comments.

Cheers

**Comment by solarissmoke** [comment]
Hi! Thanks for your recent PR. 

If you look at the [code inside WP](https://github.com/WordPress/WordPress/blob/master/wp-admin/edit-form-advanced.php#L299), the `commentsdiv` is only added if the post type supports comments, or if the post already has comments. Same goes for `commentstatusdiv` and `trackbacksdiv`.

The plugin removes support for comments [here](https://github.com/solarissmoke/disable-comments/blob/master/disable-comments.php#L150) so the only time the meta box will be available is if the post already has comments on it.

In the past I have looked at whether to force removal of the box even if the post has comments, but after user feedback have decided it is best to let admins remove comments manually before using the plugin.

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke,

That makes sense, I'd noticed it appeared on my test install but that was due to the Hello World post having the default comment on it. 

How do I go about reverting that portion of my PR? 

Might be a good idea to provide a tool which purges all existing comments which requires users to init as I know when I disable comments I normally want all mine purged as well.

Let me know how to proceed.

Thanks

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke for your feedback, I've reverted my change for this issue.

Created an issue for providing a purge tool;
https://github.com/solarissmoke/disable-comments/issues/33

And found another issue, if you have comments disabled you can't delete an existing comment out of the comments metabox on a post.
https://github.com/solarissmoke/disable-comments/issues/34

Cheers

**Comment by solarissmoke** [comment]
Closing this issue. In future, please make separate PRs for each change, and do each from a separate branch in your fork. As it is currently your PR includes all the proposed changes (some of which I want to merge, others you have reverted) and it makes merging a bit tricky ;-).

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke, sorry for the delay and improper process for PRs. I just got back from summer holidays. Appreciate you closing and handling the tricky merging.
Cheers
