### ISSUE TITLE
Remove the 'Turn comments on and off' link in the Wordpress Welcome

### ISSUE THREAD

**Issue by garrett-eclipse** [solarissmoke/disable-comments#30]
Creating a ticket to log this issue before resolving.

On the Welcome Panel there's a link to the Discussions panel which if all commenting disabled just goes to the disabled message. Am going to remove via JS;
![screen shot 2016-05-13 at 12 02 35 pm](https://cloud.githubusercontent.com/assets/8726005/15258889/d19a2e4e-1902-11e6-998c-bae9a10b537e.png)

Cheers

**Comment by solarissmoke** [comment]
I'm wondering whether it's really worth it for something that people only see once. Overall I want to keep the plugin as lightweight as possible.

**Comment by garrett-eclipse** [comment]
Hi @solarissmoke, I agree about keeping things lightweight. I don't feel this is really bloat and can be targeted to the dashboard so as not to slow any other pages. I've reset my fork and will supply updated code in a branched pull request.
The use case I prefer this for is when providing clients with their new Wordpress site I often leave the Welcome Panel open as a intro for the user. With the 'Turn comments on or off' items I'd had one or two people asking about it and had to inform them that I've already disabled this globally, by removing this line I remove the need for that question.
Cheers

**Comment by solarissmoke** [comment]
Fixed in #36.
