### ISSUE TITLE
Remove the 'Comments RSS' link within the Meta Widget

### ISSUE THREAD

**Issue by garrett-eclipse** [solarissmoke/disable-comments#31]
Logging a ticket before making change to hide the Comments RSS link within the Meta Widget;
![screen shot 2016-05-13 at 12 23 03 pm](https://cloud.githubusercontent.com/assets/8726005/15259328/768b909e-1905-11e6-8f6c-b7c4a502637f.png)

**Comment by solarissmoke** [comment]
Thanks for this - a few comments:

- We should not be adding this JS to every site indiscriminately. It should be possible to check whether the Meta widget is active before deciding whether to render this JS. 

- Would be better to add the JS to the footer instead of the `head`.

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke, good call. Is there a check that can be used to determine if the widget is enabled. Or is there an action on the widget we can tie into.
Cheers

**Comment by solarissmoke** [comment]
[`is_widget_active`](https://codex.wordpress.org/Function_Reference/is_active_widget) is probably what you want.

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke, I've moved the snippet to wp_footer and introduced the is_active_widget conditional.

**Comment by garrett-eclipse** [comment]
Thanks for pushing this out @solarissmoke, tested it with 1.5.1 successfully. And I liked the additional check for jquery, had never seen that wp_script_is function before definitely a good call. Cheers
