### ISSUE TITLE
Enhancement - Provide a purge tool for bulk deleting all comments

### ISSUE THREAD

**Issue by garrett-eclipse** [solarissmoke/disable-comments#33]
Please introduce a bulk tool for purging all existing comments from a website.

From #29;
"Might be a good idea to provide a tool which purges all existing comments which requires users to init as I know when I disable comments I normally want all mine purged as well."

**Comment by garrett-eclipse** [comment]
@solarissmoke I was thinking of repurposing the Delete All Comment plugin code for this.
https://en-ca.wordpress.org/plugins/delete-all-comments/

What do you suggest on approach, should the tool just be added to the settings or should a separate tool page be introduced?

Thank you

**Comment by solarissmoke** [comment]
Thanks for this and the other issues (which I hope to look at in the next week or so).
I think it would be better to have a button to purge existing comments on the current settings page rather than add another page to the admin. PR for this is welcome!

**Comment by garrett-eclipse** [comment]
Hey @solarissmoke I've introduced this functionality as depicted here;
![screen shot 2016-06-01 at 12 50 51 pm](https://cloud.githubusercontent.com/assets/8726005/15723556/d5ce05b8-27f7-11e6-98cb-bb9463db2023.png)

The settings default to what's specified on the Disable Comments options. 
If delete everywhere I truncate the commentmeta and comments tables and set comment_count to 0 on all posts.
If delete by post type I remove the commentmeta and comments associated with all posts of post_type specified.

The tool is disabled if no comments are available.

I haven't tested in Multi-site so please do as I don't have an instance. And I haven't pushed this to the Must-Use plugin, so please migrate the changes into that repo/plugin as well please.

Thank you

**Comment by solarissmoke** [comment]
Thanks. Please can you make a new PR for this change only as your other PR combines too many other changes. I have made some comments on [this commit](https://github.com/garrett-eclipse/disable-comments/commit/756b35e8a3ca7204845714674f56db5c4d741e45).

**Comment by garrett-eclipse** [comment]
Alright, I think I did it the right way this time. Sorry about that. So I set-up a new fork, branch and PR for this feature. I've also made little comments on your commit messages and included fixes for most items. 
You mentioned the WP Database API and was hoping you could clarify as I only know about $wpdb and nothing more specific than doing a prepare or query.
Thanks @solarissmoke, appreciate your work

**Comment by solarissmoke** [comment]
Sorry for the delay in reviewing this. I have made a couple of comments in the code. Apart from that I think we should move this functionality onto a separate page. Having tried it I think there is a risk of people submitting the wrong form which could cause accidental deletion of comments...

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke 
Good call, I'll migrate it to a tool page as it's not really settings and push an update for review.
Cheers

**Comment by solarissmoke** [comment]
Fixed in 6791ce7383ce4c8bd0c2acaf77f6debe853d600e

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke
