### ISSUE TITLE
Disable Comments blocks the ability to interact with existing Comments on a post

### ISSUE THREAD

**Issue by garrett-eclipse** [solarissmoke/disable-comments#34]
Hello,

I found with existing comments that are listed in the commentsdiv metabox that their actions (Trash, Spam, etc) are all broken due to disable comments.
![screen shot 2016-05-18 at 10 58 42 am](https://cloud.githubusercontent.com/assets/8726005/15369613/40ba0a2c-1ce8-11e6-957a-9003d44260fa.png)

Interacting with the comment results in the 'Comments are closed' page;
![screen shot 2016-05-18 at 10 58 49 am](https://cloud.githubusercontent.com/assets/8726005/15369633/59c7f83a-1ce8-11e6-8ba3-ed403a2ce693.png)

@solarissmoke Do you feel it better to disable the action links or allow actions to bypass the redirect conditional? It appears they all have action param so can do a $_GET['action'] check;
http://localhost:8888/comments/wp-admin/comment.php?c=1&action=trashcomment&_wpnonce=333f724816

Thanks

**Comment by solarissmoke** [comment]
I don't think it is worth worrying about this too much, especially if we are adding a tool to delete comments. I think the documentation already says that you need to delete existing comments before enabling the plugin.

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke, I'm fine with that.
If we change our minds we can either update the conditional within filter_admin_menu to check there's a $_GET['action'] like so;
`if ( ! isset($_GET['action']) && ($pagenow == 'comment.php' || $pagenow == 'edit-comments.php' || $pagenow == 'options-discussion.php' ) )`
OR, we can remove the comments links using the comment_row_actions filter as follows;
`
public function remove_comment_actions( $actions, $comment ) {
	return array();
}
add_filter( 'comment_row_actions', array( $this, 'remove_comment_actions' ), 10, 2 );
`
*Of course probably need to do a check that all comments are disabled.

These options may reduce user frustrating when they get to the error screen which has no way of navigating off of without using back button.

Let me know if you want me to put in the action filter or allow the $_GET['action'] bypass.

Cheers

**Comment by solarissmoke** [comment]
I'm closing this for the time being - we can only help users so much and the documentation clearly says that you should remove existing comments before activating the plugin.
