### ISSUE TITLE
"Loading comments" still showing to the user

### ISSUE THREAD

**Issue by JonathanHuot** [solarissmoke/disable-comments#38]
Hi,
When all comments are disabled, if I open a media from a gallery, I have a short period where users can see "Loading comments", then it disappears (if comments are enabled, it is the same location where we can add a new comment).

I don't know if this plugin can do something about it, but that would be wonderful :-)

Thanks for trying to do something which must be provided by default to Wordpress.

**Comment by solarissmoke** [comment]
This is an issue with your theme unfortunately - not much that can be done about it from this end. There are some suggestions on how you can deal with this kind of issue in the [FAQs](https://wordpress.org/plugins/disable-comments/faq/).
