### ISSUE TITLE
Multisite - Remove First Comment fields/functionality from Network Activated Sites

### ISSUE THREAD

**Issue by garrett-eclipse** [solarissmoke/disable-comments#40]
Hey @solarissmoke 

While testing my update on a Network Activated site I noticed the First Comment fields under Network Settings;
![screen shot 2016-11-07 at 7 21 47 pm](https://cloud.githubusercontent.com/assets/8726005/20085699/ae631608-a51f-11e6-93d9-3760be17ad56.png)

When Comments are disabled Everywhere there's no point in a First Comment being generated on Site creation.

If this is something the plugin should remove then we'll want to not only account for the fields but their saved options and ensure that the First Comment functionality is disabled so new sites don't get an initial comment.

Thoughts?
Thanks

**Comment by garrett-eclipse** [comment]
Digging into Wordpress core there's no way to suppress the first comment creation so will have to be done after the fact like this example;
http://wordpress.stackexchange.com/a/135298

And to save future digging the site option names are;
first_comment_author
first_comment_email
first_comment_url
first_comment

Looks like they aren't filterable either so we'll have to hide the fields via jQuery.

**Comment by solarissmoke** [comment]
We can only fight WordPress so much - comments are baked hard into the core and I am not keen on using JS etc to work around this.
