### ISSUE TITLE
Pingback not removed

### ISSUE THREAD

**Issue by senlin** [solarissmoke/disable-comments#46]
In the [readme.txt file L60](https://github.com/solarissmoke/disable-comments/blob/master/readme.txt#L60) it says that the pingback is removed, but on a vanilla install (WP 4.9.2) the pingback has been added to the `<head>`: 
```
<link rel="pingback" href="http://domain.dev/xmlrpc.php">
```

**Comment by solarissmoke** [comment]
That line in the readme refers to the `X-Pingback` HTTP header, not to the `link` tag inserted in the HTML. 

Unfortunately the latter is controlled by your theme, and even WP's own themes until Twentysixteen insert this unconditionally without checking whether pings are open. If you check your theme template you will see it is rendering this link tag - there's no easy way for a plugin to override that.
