### ISSUE TITLE
Conflict with CF7 Blacklist

### ISSUE THREAD

**Issue by garrett-eclipse** [solarissmoke/disable-comments#48]
Hi @solarissmoke I came across this while using CF7. They support the comment blacklist as a way to provide more spam filtering controls, more info;
https://contactform7.com/comment-blacklist/

With Disable Comments in place the Settings > Discussions page is removed which removes the ability for CF7 users to access the blacklist.

Wondering if you think I should submit a PR to enable the Discussions page when CF7 is in place.

Thanks

**Comment by solarissmoke** [comment]
I am not too keen on special-casing for individual plugins, as maintaining compatibility with WordPress as well as other plugins increases the complexity in a way I want to avoid.

If it's a problem I would prefer instead just to not remove that settings page - guess it depends on how many people this is an issue for (vote here if you have an opinion).

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke 

I fully appreciate that, putting in a bunch of compat code that may change in the future introducing a maintenance nuisance.

Looking at the available filters was thinking I could just put in a remove_action for filter_admin_menu but then that restores the edit-comments.php which I don't want. I guess I can remove and then re-add it but was wondering to give finer controls would you be up for me pushing a PR splitting filter_admin_menu into two functions one for the comments interface and the other for the options so a plugin or custom code could disable with finer controls?

Let me know and I'll be happy to submit that as it then allows me to re-enable the options page specifically for my client using the CF7 blacklist.

Appreciated

**Comment by solarissmoke** [comment]
How about taking a similar approach to [what is done here](https://github.com/solarissmoke/disable-comments/blob/e032d4a5053d5e430ff4455d8b03e9aadb996c79/disable-comments.php#L446-L450) - i.e., look for a `define()` that can be used to control whether the admin menu is filtered?

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke I like that idea, sorry got pulled away before I could finish my PR.

I setup a new `discussion_settings_allowed` setting controlled by a `define()` of `DISABLE_COMMENTS_ALLOW_DISCUSSION_SETTINGS`. 

That first commit was a bit rushed, I've cleaned it up and tested now, let me know what you think.

**Comment by garrett-eclipse** [comment]
With the merge of #49 this is resolved
