### ISSUE TITLE
Can't show Comments after disable plug in.

### ISSUE THREAD

**Issue by luochenzhimu** [solarissmoke/disable-comments#54]
Can't show Comments after disable plug in. How can I revert it.

**Comment by solarissmoke** [comment]
Please read and https://wordpress.org/support/topic/how-to-re-enable-comments-after-using-persistent-mode/ for common causes for this https://wordpress.org/support/topic/comments-off-when-disabled/. Unfortunately I'm not able to provide support on an individual basis.
