### ISSUE TITLE
Incompatible with Wordpress 5.0

### ISSUE THREAD

**Issue by gjedeer** [solarissmoke/disable-comments#57]
When adding or editing post, the editor is not visible. The error log shows:

```
PHP Notice:  edit_form_advanced is <strong>deprecated</strong> since version 5.0.0! Use block_editor_meta_box_hidden_fields instead. This action is still supported in the classic editor, but is deprecated in the block editor. in /var/www/wp-includes/functions.php on line 4147
```

After disabling this plugin, Wordpress goes back to normall - adding posts is possible.

**Comment by gjedeer** [comment]
After commenting out this line https://github.com/solarissmoke/disable-comments/blob/master/disable-comments.php#L186 and enabling plugin, the editor works too.

Perhaps this would work:

```
if(version_compare(get_bloginfo('version'),'5.0.0', '<') ) {
    add_action( 'edit_form_advanced', array( $this, 'edit_form_inputs' ) );
}
```

**Comment by garrett-eclipse** [comment]
Thanks @gjedeer for the report.

It seems the WSOD is a core issue - https://core.trac.wordpress.org/ticket/45341
Seems it's related to this as well (Disabled Comments was mentioned and I requested it reopen) - https://github.com/WordPress/gutenberg/issues/10929
*As mentioned at the end of this article (https://wordpress.org/support/topic/classic-editor-is-blank-in-wordpress-5-0/) it's a warning and not an error.

So for the time being in your production keep the logging disabled.

For support of 5.0/GB it appears the hidden input added in `edit_form_inputs` will need to move to `block_editor_meta_box_hidden_fields` or be added conditionally. Thanks for the snippet, that coupled with a check for the Classic Editor should suffice. I'll take a look further when I can.

**Comment by garrett-eclipse** [comment]
A more appropriate core ticket as it's the one introducing `block_editor_meta_box_hidden_fields`;
https://core.trac.wordpress.org/ticket/45283

**Comment by gjedeer** [comment]
Woah, what a mess. Thank you for looking into it - it seems that it will take a while until they stabilize an interface and a hack is needed until then

**Comment by solarissmoke** [comment]
I have removed all use of the `edit_form_inputs` in version 1.9.0, which will hopefully resolve this issue.

**Comment by gjedeer** [comment]
Thanks!
