### ISSUE TITLE
Suppress the 'Latest Comments' block in Gutenberg when comments are disabled everywhere

### ISSUE THREAD

**Issue by garrett-eclipse** [solarissmoke/disable-comments#60]
Hello Samir,

I wanted your thoughts on a small enhancement for further WP 5.0 (Gutenberg) support. In the editor there's a 'Latest Comments' block which if you've disabled comments everywhere would be nice to remove.

<img width="387" alt="screen shot 2019-03-03 at 2 05 59 am" src="https://user-images.githubusercontent.com/8726005/53693755-8dafc080-3d59-11e9-9abb-4dce73dbb649.png">

If you've disabled comments but haven't removed them this widget will display those unremoved comments. If there's no comments it just displays a 'No comments to show'.

What are your thoughts on removing the block when Disable Comments is set to everywhere?

Thanks

**Comment by solarissmoke** [comment]
Hi @garrett-eclipse, this sounds like a good idea to me.

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke I'll take a stab at this when I have some free time. Cheers
