### ISSUE TITLE
1.10.0 kills Yoast panel, unable to load JS

### ISSUE THREAD

**Issue by EyesX** [solarissmoke/disable-comments#70]
In version 1.10.0 Disable Comments kills Yoast SEO panel on post.php using Classic editor (Not tested with Gutenbug).

`post.php?post=269&action=edit:292 GET https://***.se/wp-content/plugins/disable-comments/assets/disable-comments.js?ver=5.2.2 net::ERR_ABORTED 404
load-scripts.php?c=0…e,utils&ver=5.2.2:8

post.php?post=269&action=edit:292 GET https://***.se/wp-content/plugins/disable-comments/assets/disable-comments.js?ver=5.2.2 404`

**Comment by solarissmoke** [comment]
Thanks - I had failed to commit the related JS file on svn. Should be fixed now in version 1.10.1.
